### ISSUE TITLE
The 'FRC_ExtensionPackage' package did not load correctly

### ISSUE THREAD

**Issue by Ernie3** [robotdotnet/FRC-Extension#10]
Greetings from Team 4342,

I installed the VS plugins from https://visualstudiogallery.msdn.microsoft.com/7c7f4cd1-e4bc-43bb-a9f1-072c6f1197d9 and I get an error message anytime I open the solution or click settings under the FRC menu in VS 2013 Community. See below:

![capture](https://cloud.githubusercontent.com/assets/6378488/11019666/e56c98a0-85d0-11e5-98be-5283e034f79f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6378488/11019667/e7ac7b80-85d0-11e5-8f00-bea53ef80130.PNG)

The code I am working with can be found here: https://github.com/KHS-Robotics/Demonator4-RobotDotNet (not that it really matters, although more info can't hurt)

Any insight would be appreciated. Awesome job on this guys, seems like it's a fun project and quite useful! Looking forward to the production version at kickoff

**Comment by ThadHouse** [comment]
I haven't tested on VS 2013 in a long time. It's all been using VS 2015. Do you have a copy of that ActivityLog we can look at? Ill try it on VS 2013 when I have a chance, but I do know it works correctly on 2015.

**Comment by Ernie3** [comment]
Gotcha. I will try it on 2015 (probably should be using that anyway). I cannot upload the log to GitHub since it's an unsupported file type (XML). I will email it to you. Thanks!

**Comment by ThadHouse** [comment]
Hmmm. Just realized I had VS 2013 installed, tried it, and it didn't seem to have any issues. Hopefully the error log will help fix it, but we might just end up removing VS 2013 support.

**Comment by ThadHouse** [comment]
<entry>
    <record>616</record>
    <time>2015/11/08 09:23:56.439</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [FRC_ExtensionPackage]</description>
    <guid>{5B8FEA9B-2657-4C90-8236-D82478B7D6C9}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
</activity>

Heres the relevant code from the error log. It looks like its trying to load the 14.0 version of the 12.0 shell. I'll try and see if adding a forced reference to the 12.0 version would fix the issue, and still work on systems with only 2015 installed. We don't use any features specific to 2015, so it should.

**Comment by Ernie3** [comment]
Cool. I installed 2015 and it works on 2013 now, so I guess since I have the version its looking for it's all fine and dandy in 2013.
