### ISSUE TITLE
Add Attributed Robot Template

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/FRC-Extension#11]
I created an attributed robot in the template, however I don't know how to write a good template for it. @jkoritzinsky Can you either make a project you would like to make a template and I can add it to the existing template, or modify the existing template yourself.

**Comment by jkoritzinsky** [comment]
I'll modify the existing template once I have a chance. I've got midterms now so I can't do anything for the rest of the week. Afterwards though I can do it.

**Comment by jkoritzinsky** [comment]
I'm almost done with adding the extension.  Thing is, I need to update the nupkgs in the extension for the project to even compile when first created.  Let me know which build I should grab from AppVeyor and I'll put those packages in the extension.

**Comment by ThadHouse** [comment]
You should just be able to download the newest one off of the master branch. I don't want to upload it to NuGet yet if we don't have to, so  just download the ones from here. https://ci.appveyor.com/project/robotdotnet/robotdotnet-wpilib/build/2016.0.0.27/artifacts . Come kickoff, we'll properly update everything and upload 2016 versions to the official nuget.

**Comment by jkoritzinsky** [comment]
Pushed out the changes.
